# Site settings
title: 
email: RaheemAbdulMutakabbir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. My name is Raheem Abdul. Welcome to my blog!
  Here you'll find my blog posts on code and my other
  personal interests. You could probably find my resume
  around here aswell. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://RaheemAbdul.ninja" # the base hostname & protocol for your site
twitter_username: MrBlkfx1
github_username:  MrBlkfx1
facebook_username: MrBlkfx1

# Build settings
markdown: kramdown
# Enabled Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap